version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - internal
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  internal:
    build: .
    command: npm run start:internal
    ports:
      - "4000:4000"
